---
title: "¿Los equipos del fútbol chileno tienen rendimiento constante?"
format: html
editor: visual
---

Todo aficionado al fútbol tiene un equipo favorito al cual apoya, este apoyo es en las buenas y en las malas, al cual le desea que gane siempre para que así se genere felicidad en ellos, si nos centramos en Chile podemos decir que resaltan 3 equipos cuyo nivel de popularidad es mayor (GFK Adimark), estos equipos son Colo-Colo, Universidad de Chile y Universidad Católica.

Los hinchas de estos equipos mencionados anteriormente se preguntan: ¿Como le a ido a mi club históricamente en los campeonatos?, ¿Que rival es más fácil de vencer?, ¿Como le ha ido a mi equipo frente a los otros 2 clubes más populares?,¿Qué equipo es el mejor? responder estas preguntas resulta relevante, ya que nos podría guiar a los resultados que obtendrá el equipo que la gente apoya.

Para lograr comprender mejor todos estos factores, se realizará un análisis a los datos obtenidos de <https://www.kaggle.com/datasets/clementeortuzar/resultados-primera-divisin-chile> que contiene los resultados del futbol Chileno desde Junio del año 2008 a Mayo del año 2021. Se analizarán los factores tanto el juego de local, como el juego de visita, los enfrentamientos directos entre los clubes más populares, a su vez apoyado por la información de ANFP para saber qué equipo salió campeón ese año y si se relaciona con el rendimiento de los equipos analizados.

Este proyecto se iniciará con la filtración por año para ver cada uno de los rendimientos de los equipos, luego se hará una comparación a nivel general de a cuál equipo le ha ido mejor a lo largo de los años y si esto se relaciona con la cantidad de campeonatos ganados en esos años, a su vez veremos si estos tienen un rendimiento constante a través de los años. Continuando se realizará una comparativa en los enfrentamientos directos entre los 3 equipos antes mencionados, una vez realizada la comparativa se concluirá cual de estos equipos es el mejor del futbol chileno entre los años 2009 y 2020 en base a su rendimiento general y rendimiento frente a los otros 2 clubes más populares del país.
